import keyboard
import time

names = [
    "AADITHYA MADHAV", "AAISHA NAJEEB", "AAYSHA RAHMAN", "ABHAY", "ABHIJITH", 
    "ABHIMANYU", "ABHINAV", "ABHIRAMI", "ADITHYA NAIR", "AFIA", "AFRIN", 
    "AFSAL", "AHAMED THANVEER", "AKSHARA", "AKSHAYA", "ALAN M", "ALEX", 
    "ANANYA", "ANEENA", "ANTONY", "ASALAKSHMI", "ASIL MEHABOOB", "ATHUL KRISHNA", 
    "BENFRANKLIN", "BINAHA MARY","CHITRA MISS", "CHRISTI", "CHRISTOS SAM", "DEON", "DHYANJITH", 
    "ELVIN", "FELIX", "GAUTHAM", "GOKUL", "GOWRI", "GRAJEL", "HIBA ANN", 
    "JAIS", "JISHNU", "JISS MARIA", "JONATHAN", "KRISHNADAS", 
    "KRISHNAPRASAD", "KRISHNAPRIYA", "MAIZAH", "MIDHUN", "MOHIT", "NAMISH", 
    "NANDANA", "NEVIN", "NIVYA", "PHILIP", "RAHUL", "RICHA", "RIJU", "ROY", 
    "SAIRA", "SANDRA", "SANJAY", "SHAKKIRA", "SHAUN GEORGE", "SHAUN JAMES", 
    "SONAM", "SOORYANARAYANAN", "SREYAS", "SRIRAM", "SRUTHI", "SURYA SURESH", 
    "THANSEEH", "THOMAS", "VINAYA", "VISHNU"
]


for name in names:
    keyboard.write(name)
    keyboard.press_and_release('tab')
    time.sleep(0.2)